-- Chat transcript log for the Ask Ari widget.
-- A session is one visitor's conversation thread (one page visit);
-- messages belong to a session in chronological order.

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,               -- UUID generated by the widget per page visit
  started_at TEXT NOT NULL,          -- ISO 8601 UTC
  last_active_at TEXT NOT NULL,      -- ISO 8601 UTC, bumped on every message
  message_count INTEGER NOT NULL DEFAULT 0,
  client_ip TEXT,                    -- bot-spam signal
  country TEXT,                      -- from request.cf
  user_agent TEXT                    -- bot-spam signal
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL REFERENCES sessions(id),
  role TEXT NOT NULL,                -- 'user' | 'ari'
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ok', -- 'ok' | 'rate_limited' | 'upstream_error'
  created_at TEXT NOT NULL           -- ISO 8601 UTC
);

CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, id);
CREATE INDEX IF NOT EXISTS idx_sessions_last_active ON sessions(last_active_at DESC);
